repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    sha: v1.0.4
    hooks:
    - id: python-bandit-vulnerability-check
-   repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.31.0
    hooks:
    - id: terraform_fmt
