version: "3.7"
services:
  webserver:
    build: .
    stdin_open: true
    # command: bash
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ${HOME}/.aws:/home/debian/.aws  # AWS Creds
      - ${HOME}/.config/gcloud:/home/debian/.config/gcloud  # GCloud Creds
      - ./:/home/debian/webserver  # This dir to workdir
